apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nats
  name: nats-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nats
    spec:
      containers:
        - image: nats-streaming
          name: nats
          args: [
              "-p",
              "4222",
              "-m",
              "8222",
              "-hbi", # how ofent its going to do a hirbid request to the client
              "5s",
              "-hbt",
              "5s",
              "-hbf", # how many attempts before, being removed
              "2",
              "-SD",
              "-cid", # cluster id
              "blockchain",
            ]
          resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: nats-srv
spec:
  selector:
    app: nats
  ports:
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: monitoring
      protocol: TCP
      port: 8222
      targetPort: 8222
