# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   creationTimestamp: null
#   labels:
#     app: proxy
#   name: proxy
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: proxy
#   strategy: {}
#   template:
#     metadata:
#       creationTimestamp: null
#       labels:
#         app: proxy
#     spec:
#       containers:
#         - image: mcuve/nginx-proxy
#           name: nginx-proxy
#           ports:
#             - containerPort: 80
#           resources: {}
# status: {}

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   creationTimestamp: null
#   labels:
#     app: proxy
#   name: proxy-srv
# spec:
#   ports:
#     - port: 80
#       protocol: TCP
#       targetPort: 80
#       nodePort: 30008

#   selector:
#     app: proxy
#   type: NodePort
# status:
#   loadBalancer: {}
